language: node_js
node_js:
- '8'
- '10'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  matrix:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: T4n0dMd1sciio4mu4LPVB8aSto00FPlup+7Bhb1EO654W8Vt4153Fo6tb2XAKxX1SjZ6iDwteYKCcVvWoOq1clkPka2RRXLb0QOgrgHRVeX8NIfAR3ntrXUr3pkJ1rPIEKT7ZHD+vuqJEK2ihgl+ibtvtJGJHOxgNyxEPSaLXAoPH0IB4suggYg+5/RW1M9HbDD7uyTO0zxjZ9ozCwZKZpl7y6yq+rAUXG88xp8rmPtapkh498JRrsqDOiyX94bzlxxA24mkMf9AkeonEQf605Ri6DfewTAIdVc4jSMlrcQ/tugXGszJo6oMudaVHDw/TRVFNWtlnqYYYdsIjvMCN7Ek/f6JGAiBCKEJFWygVJnGb8OYnFOHFfb+DhG1jR/GukVfbW76qP1WIC/9IJBGNCWo44dCsN/f5Qj9NPqliHuMf1tw52vWndk6BqMRE72059QXCXox+chp9jUhrZ/zQGWf6DDpt9MUYPdWRjb+6DpGJdAM1KeV8w8PY2VP6EfreG97AwxeIlJIEm5rj6s8HHMvrl4tVn0vO6VR9agYPRTuEgXjx3tOlnImmaMiyeIoguVbaIIT8Uw5/3/dIAYEpXxDJaJR4uUuU4fg+Fj0ZYoKyrLb5Z2rGGs6P5WJkJw2pEFOOK6AfIHE71QxZCX5zirgOe94rFaYzjfs6ivSEY8=
    file:
      - remark-shortcodes.js
      - remark-shortcodes.min.js
    on:
      tags: true
      repo: djm/remark-shortcodes
      node: '10'
  - provider: npm
    email: mail@djm.org.uk
    api_key:
      secure: A2mFnvw7GUefS73OwUKJM22LeQwxn0+o+Vlne5ovQO/QrSNjoTEMSJq/osrA7OUAZo0Kf/x0EyJyBNGzEExznfoHIwHyiELdMTDOw0Rjv2K1IlJtvRvix21d3NAaONj87CcBTf8XiX96EYa+BjL/phGQC9wUG+G7BQFp0wQMNCwc+0UB975IyLhk4UH8ely6MNIzu5CuNqASTUonGJBJ7+quo2dPfxQ0q9EPzzZ4K77V7jhaPXTBdAjBZpPdTUqDfXZ66Tk1bA763ZnBIOGtJcI66liMzipaHtH9aqlYoo72a8Msln7dtizB8EUq2etEfb+euIqU2pCtOmU3zxndEmOFWGW9mjls4Ahvrb6GbltKeiC29vdE2J8sIkdtDyrnjRHxu7cJQFAPtKFmqDr1gmAv/CB7FZhkCYjxDwuenYAUS49x6h6hCQ8OLLnM7B5SVQzJ/BozQKq7ULxXJkO60+DlF5UptbuATJ9waL7D2NsJLN2JfFKSvcNoYt5GA1CSQhwHLx/ToD0CwZocT5I+egzBOnCthompMoReqiiqPF4B/X2qe9Le67dv1kPa+dAXPtxrHejxgtDvAWzO05YcuWsFht5d6hzlyREsTGZOeR72p2uiGGKn2sHHdmfgSb00pdDQXeK81IHShIwdvolBTLdxWqmlwvBeIs2+EGdSlAA=
    on:
      tags: true
      repo: djm/remark-shortcodes
      node: '10'
