language: node_js
node_js:
- '8'
- '10'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: T4n0dMd1sciio4mu4LPVB8aSto00FPlup+7Bhb1EO654W8Vt4153Fo6tb2XAKxX1SjZ6iDwteYKCcVvWoOq1clkPka2RRXLb0QOgrgHRVeX8NIfAR3ntrXUr3pkJ1rPIEKT7ZHD+vuqJEK2ihgl+ibtvtJGJHOxgNyxEPSaLXAoPH0IB4suggYg+5/RW1M9HbDD7uyTO0zxjZ9ozCwZKZpl7y6yq+rAUXG88xp8rmPtapkh498JRrsqDOiyX94bzlxxA24mkMf9AkeonEQf605Ri6DfewTAIdVc4jSMlrcQ/tugXGszJo6oMudaVHDw/TRVFNWtlnqYYYdsIjvMCN7Ek/f6JGAiBCKEJFWygVJnGb8OYnFOHFfb+DhG1jR/GukVfbW76qP1WIC/9IJBGNCWo44dCsN/f5Qj9NPqliHuMf1tw52vWndk6BqMRE72059QXCXox+chp9jUhrZ/zQGWf6DDpt9MUYPdWRjb+6DpGJdAM1KeV8w8PY2VP6EfreG97AwxeIlJIEm5rj6s8HHMvrl4tVn0vO6VR9agYPRTuEgXjx3tOlnImmaMiyeIoguVbaIIT8Uw5/3/dIAYEpXxDJaJR4uUuU4fg+Fj0ZYoKyrLb5Z2rGGs6P5WJkJw2pEFOOK6AfIHE71QxZCX5zirgOe94rFaYzjfs6ivSEY8=
    file:
      - remark-shortcodes.js
      - remark-shortcodes.min.js
    on:
      tags: true
      repo: djm/remark-shortcodes
      node: '10'
  - provider: npm
    email: mail@djm.org.uk
    api_key:
      secure: VnS5vTz721ZKtpgoP/Z3zbY0eTa7ya3glRWwdYGkg7AboIbbCxtRK7w6oGWzl4lMzYr11P4VCim5gcT1G5crOnVVkm9zVR84KoANndmC6GZbmA4ECW25OYpAeQgjyFGgCSwY1Wd3P9yUZbk7xSYJTQ8GZrhXp8e29oRaRWObAEzdXU01WlkWLdAZm49vcyed3mh8Y7OgZS/+MsKDe2p+zPhX182ufq2a1t6JCe3fG2Kbr/4agrz8H8d5RQLuz+EOJx91nXKaySJ39VZj5E0Cq/TVJU7a7X2jXZwqeEYoM+IHjZ2QRsnrmozRt6Nf8eNT2vgf1eJr4W2Mo3G1eL4wRA1+g6/e63yzvYKBLmgwSTLCjaRdI2ATL/pvQluL1y3EkNI6aoiKBevlDAPigkf8lQ4sj/4rvA09UmjC7296lh8F3n7dIPrPnE83ICG5IVFirsN2+3dZgbN4Xbxohghea9/o5FqPR1z8f3zG3eUxn220ahym/XnwXE7b4gSBH4Pj8+xoHTQQ+0ieWGu7z15vJQxQUij6+H7xfEWeX2sQ1o3KyKU7HBqa4uyKO2EwiqWzziMMoHT19QYlSBVAyZmS+uS4eXorBcfHOZa7qQf9zclstz7HUGmFBU/vj+8iFx0V/Xp9AKAkKLI7mX+1XV3BxFA+J2kZ6tKsl7S1iMxb1aM=
    on:
      tags: true
      repo: djm/remark-shortcodes
      node: '10'
